import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-4xl px-6 lg:max-w-6xl lg:px-8">
          <Nav/>
          <main className='p-4 mt-10 mx-auto max-w-3xl pb-10'>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
